server:
  port: 8080

jwt:
  key_path: secret/private.key

cron:
  str: "*/2 * * * *"  # every minute. Try https://crontab.cronhub.io

database:
  url: "postgresql://root:root@localhost:5434/bond_picker?"