/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as RegistrationRouteImport } from './routes/registration'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AppRouteImport } from './routes/app'
import { Route as AppPickerRouteImport } from './routes/app/picker'
import { Route as AppChosenRouteImport } from './routes/app/chosen'

const RegistrationRoute = RegistrationRouteImport.update({
  id: '/registration',
  path: '/registration',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const AppPickerRoute = AppPickerRouteImport.update({
  id: '/picker',
  path: '/picker',
  getParentRoute: () => AppRoute,
} as any)
const AppChosenRoute = AppChosenRouteImport.update({
  id: '/chosen',
  path: '/chosen',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/app': typeof AppRouteWithChildren
  '/login': typeof LoginRoute
  '/registration': typeof RegistrationRoute
  '/app/chosen': typeof AppChosenRoute
  '/app/picker': typeof AppPickerRoute
}
export interface FileRoutesByTo {
  '/app': typeof AppRouteWithChildren
  '/login': typeof LoginRoute
  '/registration': typeof RegistrationRoute
  '/app/chosen': typeof AppChosenRoute
  '/app/picker': typeof AppPickerRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/app': typeof AppRouteWithChildren
  '/login': typeof LoginRoute
  '/registration': typeof RegistrationRoute
  '/app/chosen': typeof AppChosenRoute
  '/app/picker': typeof AppPickerRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/app' | '/login' | '/registration' | '/app/chosen' | '/app/picker'
  fileRoutesByTo: FileRoutesByTo
  to: '/app' | '/login' | '/registration' | '/app/chosen' | '/app/picker'
  id:
    | '__root__'
    | '/app'
    | '/login'
    | '/registration'
    | '/app/chosen'
    | '/app/picker'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AppRoute: typeof AppRouteWithChildren
  LoginRoute: typeof LoginRoute
  RegistrationRoute: typeof RegistrationRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/registration': {
      id: '/registration'
      path: '/registration'
      fullPath: '/registration'
      preLoaderRoute: typeof RegistrationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/picker': {
      id: '/app/picker'
      path: '/picker'
      fullPath: '/app/picker'
      preLoaderRoute: typeof AppPickerRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/chosen': {
      id: '/app/chosen'
      path: '/chosen'
      fullPath: '/app/chosen'
      preLoaderRoute: typeof AppChosenRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppChosenRoute: typeof AppChosenRoute
  AppPickerRoute: typeof AppPickerRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppChosenRoute: AppChosenRoute,
  AppPickerRoute: AppPickerRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AppRoute: AppRouteWithChildren,
  LoginRoute: LoginRoute,
  RegistrationRoute: RegistrationRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
